### ISSUE TITLE
daylight savings error

### ISSUE THREAD

**Issue by swati-patel** [reedwade/metlink-api-maybe#1]
Thanks for the code.  There's an error with the python version when parsing the date if we're in daylight savings:

ValueError: time data u'2016-12-29T15:52:00+13:00' does not match format '%Y-%m-%dT%H:%M:%S+12:00'

It works if you change the format to +13 instead of 12:

time.strptime(rfc339_timestamp, "%Y-%m-%dT%H:%M:%S+13:00")

**Comment by reedwade** [comment]
thanks for the report, I'll have a look at that -- I guess we'll need something that works all year...

**Comment by reedwade** [comment]
fixed

thanks @swati-patel !

**Comment by swati-patel** [comment]
Thanks :)
